# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': '发票', 'verbose_name_plural': '发票'},
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='billhead',
            field=models.CharField(max_length=30, verbose_name='发票抬头'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='billlocation',
            field=models.CharField(max_length=50, verbose_name='发票单位'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='billnumber',
            field=models.CharField(max_length=30, verbose_name='税务号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=6, null=True, verbose_name='性别'),
        ),
    ]
