# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170821_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(max_length=30, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号码'),
        ),
    ]
