# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170821_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='billlocation',
        ),
        migrations.AddField(
            model_name='bill',
            name='accountnumber',
            field=models.CharField(max_length=30, null=True, verbose_name='账号'),
        ),
        migrations.AddField(
            model_name='bill',
            name='address',
            field=models.CharField(max_length=30, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bank',
            field=models.CharField(max_length=30, null=True, verbose_name='开户行'),
        ),
        migrations.AddField(
            model_name='bill',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='通讯地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='email2',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='备用邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=30, null=True, verbose_name='职称'),
        ),
        migrations.AddField(
            model_name='user',
            name='officephone',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='办公电话'),
        ),
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.CharField(max_length=6, null=True, verbose_name='邮编'),
        ),
        migrations.AddField(
            model_name='user',
            name='workunit',
            field=models.CharField(max_length=255, null=True, verbose_name='工作单位'),
        ),
    ]
