# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_internetrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paycompany', models.CharField(max_length=30, verbose_name='缴费单位名称')),
                ('paytime', models.DateField(verbose_name='缴费时间')),
                ('payaccount', models.CharField(max_length=30, verbose_name='缴费账号')),
                ('remark', models.CharField(max_length=50, verbose_name='备注')),
                ('creditfile', models.FileField(upload_to='', verbose_name='凭证文件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '缴费记录',
            },
        ),
    ]
